# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import health_export_pb2 as health__export__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in health_export_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HealthExportServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExportSleep = channel.unary_unary(
                '/health.HealthExportService/ExportSleep',
                request_serializer=health__export__pb2.SleepBatch.SerializeToString,
                response_deserializer=health__export__pb2.IngestResponse.FromString,
                _registered_method=True)
        self.ExportExercise = channel.unary_unary(
                '/health.HealthExportService/ExportExercise',
                request_serializer=health__export__pb2.ExerciseBatch.SerializeToString,
                response_deserializer=health__export__pb2.IngestResponse.FromString,
                _registered_method=True)
        self.ExportGlucose = channel.unary_unary(
                '/health.HealthExportService/ExportGlucose',
                request_serializer=health__export__pb2.GlucoseBatch.SerializeToString,
                response_deserializer=health__export__pb2.IngestResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/health.HealthExportService/HealthCheck',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=health__export__pb2.IngestResponse.FromString,
                _registered_method=True)


class HealthExportServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ExportSleep(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExportExercise(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExportGlucose(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HealthExportServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExportSleep': grpc.unary_unary_rpc_method_handler(
                    servicer.ExportSleep,
                    request_deserializer=health__export__pb2.SleepBatch.FromString,
                    response_serializer=health__export__pb2.IngestResponse.SerializeToString,
            ),
            'ExportExercise': grpc.unary_unary_rpc_method_handler(
                    servicer.ExportExercise,
                    request_deserializer=health__export__pb2.ExerciseBatch.FromString,
                    response_serializer=health__export__pb2.IngestResponse.SerializeToString,
            ),
            'ExportGlucose': grpc.unary_unary_rpc_method_handler(
                    servicer.ExportGlucose,
                    request_deserializer=health__export__pb2.GlucoseBatch.FromString,
                    response_serializer=health__export__pb2.IngestResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=health__export__pb2.IngestResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'health.HealthExportService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('health.HealthExportService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HealthExportService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ExportSleep(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/health.HealthExportService/ExportSleep',
            health__export__pb2.SleepBatch.SerializeToString,
            health__export__pb2.IngestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExportExercise(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/health.HealthExportService/ExportExercise',
            health__export__pb2.ExerciseBatch.SerializeToString,
            health__export__pb2.IngestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExportGlucose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/health.HealthExportService/ExportGlucose',
            health__export__pb2.GlucoseBatch.SerializeToString,
            health__export__pb2.IngestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/health.HealthExportService/HealthCheck',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            health__export__pb2.IngestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
